version: "2"

services:
  medicare-backend:
    container_name: medicare-backend
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
    volumes:
      - data:/data/uploads
  mongo:
    container_name: mongo
    image: mongo
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
volumes:
  data:
    driver: local